# Generated by Django 4.2 on 2024-03-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='id_empresa',
            field=models.IntegerField(null=True),
        ),
    ]
