# Generated by Django 5.0.2 on 2024-02-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='foto_de_perfil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
