# Generated by Django 4.2 on 2024-03-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_empleado_id_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
