# Generated by Django 5.0.2 on 2024-02-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_empresa_foto_de_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
