# Generated by Django 4.2 on 2024-03-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_empleado_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='teléfono',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
