# Generated by Django 5.0.2 on 2024-02-29 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.CharField(max_length=32)),
                ('precio_unitario', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.proveedor')),
            ],
        ),
    ]
