# Generated by Django 4.2 on 2024-03-07 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_empleado_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_transaccion', models.CharField(max_length=32)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=32)),
                ('fecha_y_hora', models.DateTimeField()),
                ('user_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empleado')),
                ('user_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
