# Generated by Django 4.2.10 on 2024-03-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_transaccion_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='producto',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='descripcion_producto',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='nombre_producto',
            field=models.CharField(default=' ', max_length=32),
            preserve_default=False,
        ),
    ]
